version: "3.8"
services:
  registration-service:
   build: ./registration-service
   ports:
     - 8085:3004
   networks:
     - microservices-network
  login-service:
   build: ./login-service
   ports:
     - 8086:3005
   environment:
     - JWT_SECRET=your_jwt_secret
   networks:
      - microservices-network
   depends_on:
      - registration-service
  update-service:
   build: ./update-service
   ports:
     - 8084:3006
   environment:
     - JWT_SECRET=your_jwt_secret
   networks:
      - microservices-network
   depends_on:
      - registration-service
networks:
  microservices-network:
    driver: bridge