version: "3.8"
services:
  registration-service:
   build: ./registration-service
   ports:
     - 8082:3001
   networks:
     - microservices-network
  login-service:
   build: ./login-service
   ports:
     - 8083:3002
   environment:
     - JWT_SECRET=your_jwt_secret
   networks:
      - microservices-network
   depends_on:
      - registration-service
  update-service:
   build: ./update-service
   ports:
     - 8084:3003
   environment:
     - JWT_SECRET=your_jwt_secret
   networks:
      - microservices-network
   depends_on:
      - registration-service
networks:
  microservices-network:
    driver: bridge